# Generated by Django 4.1.4 on 2023-09-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belt',
            name='belt',
            field=models.CharField(max_length=32),
        ),
    ]
