# Generated by Django 4.1.4 on 2023-09-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_belt_belt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belt',
            name='belt',
            field=models.CharField(default='No Belt', max_length=32),
        ),
    ]
