# Generated by Django 4.1.4 on 2023-09-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_belt_belt'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='newAwardName',
            field=models.CharField(default='New Award', max_length=200),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(default='New Award', max_length=200),
        ),
    ]
