# Generated by Django 4.1.4 on 2023-09-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_award_newawardname_alter_award_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='newAwardName',
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(choices=[('1', 'Most Improved Musketeer'), ('2', 'Encouragement Award'), ('3', 'Best Team Leader')], max_length=200),
        ),
    ]
