# Generated by Django 4.1.4 on 2023-09-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_award_newawardname_alter_award_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belt',
            name='belt',
            field=models.CharField(max_length=32),
        ),
    ]
