# Generated by Django 4.1.4 on 2023-09-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_award_name_alter_belt_belt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.SmallIntegerField()),
                ('address_line_1', models.CharField(help_text='Street Number and Name', max_length=200)),
                ('address_line_2', models.CharField(help_text='Suburb', max_length=200)),
                ('address_line_3', models.SmallIntegerField(help_text='Postcode')),
                ('date_of_birth', models.DateField()),
                ('belt', models.CharField(choices=[('White', (('0', 'White'), ('1', 'White 1/2'), ('2', 'White 1'), ('3', 'White 1 1/2'), ('4', 'White 2'), ('5', 'White 2 1/2'), ('6', 'White 3'), ('7', 'White-Orange'))), ('Orange', (('8', 'Orange'), ('9', 'Orange 1/2'), ('10', 'Orange 1'), ('11', 'Orange 1 1/2'), ('12', 'Orange 2'), ('13', 'Orange 2 1/2'), ('14', 'Orange 3'), ('15', 'White-Yellow'))), ('Yellow', (('16', 'Yellow'), ('17', 'Yellow 1/2'), ('18', 'Yellow 1'), ('19', 'Yellow 1 1/2'), ('20', 'Yellow 2'), ('21', 'Yellow 2 1/2'), ('22', 'Yellow 3'), ('23', 'White-Blue'))), ('Blue', (('24', 'Blue'), ('25', 'Blue 1/2'), ('26', 'Blue 1'), ('27', 'Blue 1 1/2'), ('28', 'Blue 2'), ('29', 'Blue 2 1/2'), ('30', 'Blue 3'), ('31', 'White-Red'))), ('Red', (('32', 'Red'), ('33', 'Red 1/2'), ('34', 'Red 1'), ('35', 'Red 1 1/2'), ('36', 'Red 2'), ('37', 'Red 2 1/2'), ('38', 'Red 3'))), ('Cho-Dan Bo', (('39', 'Cho-Dan Bo 1'), ('40', 'Cho-Dan Bo 2'), ('41', 'Cho-Dan Bo 3'), ('42', 'Cho-Dan Bo 4'), ('43', 'Cho-Dan Bo 5'), ('44', 'Cho-Dan Bo 6'), ('45', 'Advanced Cho-Dan Bo'), ('46', 'Probationary Black Belt'))), ('Black Belt', (('47', '1st Dan'), ('48', '2nd Dan'), ('49', '3rd Dan'), ('50', '4th Dan'), ('51', '5th Dan'), ('52', '6th Dan'), ('53', '7th Dan'), ('54', '8th Dan'), ('55', '9th Dan')))], max_length=50)),
                ('awards', models.ManyToManyField(help_text='What awards has this person recieved?', to='dashboard.award')),
            ],
        ),
        migrations.DeleteModel(
            name='Belt',
        ),
    ]
