# Generated by Django 4.1.4 on 2023-09-10 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_member_delete_belt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address_line_3',
            field=models.CharField(help_text='Postcode', max_length=4),
        ),
        migrations.CreateModel(
            name='GradingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('MS', 'Musketeers'), ('JR', 'Juniors'), ('SN', 'Seniors'), ('BB', 'Black Belt')], max_length=2)),
                ('assessor', models.ManyToManyField(help_text='Who assessed this particular grading?', related_name='assessor2gradings', to='dashboard.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='member2gradings', to='dashboard.member')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('SD', 'Self Defense'), ('SE', 'Self Develop'), ('PA1', '1st Pattern'), ('PA2', '2nd Pattern'), ('PA3', '3rd Pattern'), ('BA', 'Basics - Hands and Feet')], max_length=200)),
                ('max_pts', models.SmallIntegerField()),
                ('achieved_pts', models.SmallIntegerField()),
                ('gradingresult', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.gradingresult')),
            ],
        ),
    ]
