# Generated by Django 4.1.4 on 2023-09-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_member_email_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='team_leader_instructor',
            field=models.CharField(blank=True, choices=[('T1', 'Team Leader Level 1'), ('T2', 'Team Leader Level 2'), ('T3', 'Team Leader Level 3'), ('T4', 'Team Leader Level 4'), ('T5', 'Team Leader Level 5'), ('IT', 'Trainee Instructor'), ('IA', 'Assistant Instructor'), ('II', 'Instructor'), ('IS', 'Senior Instructor'), ('IH', 'Head Instructor')], max_length=2),
        ),
    ]
