# Generated by Django 4.2.4 on 2023-09-12 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_member_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='id_number',
            new_name='idnumber',
        ),
    ]
