# Generated by Django 4.1.4 on 2023-09-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_member_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingresult',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
