# Generated by Django 4.1.4 on 2023-09-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_gradingresult_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradingresult',
            old_name='for_belt',
            new_name='forbelt',
        ),
    ]
