# Generated by Django 4.2.5 on 2023-09-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradingresult',
            options={'ordering': ['date', 'member__idnumber']},
        ),
    ]
