# Generated by Django 4.2.5 on 2023-09-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_gradingresult_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingresult',
            name='award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dashboard.award', verbose_name='Award'),
        ),
    ]
