# Generated by Django 4.2.5 on 2023-09-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_gradingresult_award'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradingresult',
            options={'ordering': ['-date', 'member__idnumber']},
        ),
    ]
