# Generated by Django 4.2.5 on 2023-09-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_gradingresult_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradingresult',
            options={'ordering': ['-date', 'type', '-forbelt', 'member__idnumber']},
        ),
    ]
