# Generated by Django 4.2.4 on 2023-12-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_gradingresult_forbelt_alter_member_belt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('type', models.CharField(choices=[('MS', 'Musketeers'), ('JR', 'Juniors'), ('SN', 'Seniors'), ('BB', 'Black Belt')], max_length=2)),
                ('instructors', models.ManyToManyField(help_text='Who taught this class?', related_name='instructors2classes', to='dashboard.member')),
                ('students', models.ManyToManyField(help_text='Who attended this class?', related_name='students2classes', to='dashboard.member')),
            ],
        ),
    ]
