# Generated by Django 4.2.4 on 2023-12-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='type',
            field=models.CharField(choices=[('MS', 'Musketeers'), ('JR', 'Juniors'), ('SN', 'Seniors'), ('BB', 'Black Belt'), ('BJ', 'BJJ'), ('BO', 'Boxing'), ('MA', 'MMA')], max_length=2),
        ),
        migrations.AlterField(
            model_name='gradingresult',
            name='type',
            field=models.CharField(choices=[('MS', 'Musketeers'), ('JR', 'Juniors'), ('SN', 'Seniors'), ('BB', 'Black Belt'), ('BJ', 'BJJ'), ('BO', 'Boxing'), ('MA', 'MMA')], max_length=2),
        ),
    ]
