# Generated by Django 4.2.4 on 2023-12-04 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_class_type_alter_gradingresult_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='start',
            field=models.TimeField(),
        ),
    ]
