# Generated by Django 4.2.4 on 2023-12-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_member_address_line_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='instructors',
            field=models.ManyToManyField(blank=True, help_text='Who taught this class?', related_name='instructors2classes', to='dashboard.member'),
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Who attended this class?', related_name='students2classes', to='dashboard.member'),
        ),
    ]
