# Generated by Django 4.1.4 on 2023-12-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_payment_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_due', 'paymenttype']},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amount_due',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='due',
            new_name='date_due',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paid',
            new_name='date_paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount currently paid, in $', max_digits=7),
        ),
    ]
