# Generated by Django 4.1.4 on 2023-12-27 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
