# Generated by Django 4.1.4 on 2023-12-27 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_payment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(help_text='Who needs to pay this?', on_delete=django.db.models.deletion.PROTECT, to='dashboard.member'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymenttype',
            field=models.ForeignKey(help_text='What type of payment is this?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.paymenttype', verbose_name='Payment Type'),
        ),
    ]
