# Generated by Django 4.1.4 on 2023-12-27 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_alter_payment_member_alter_payment_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymenttype',
            field=models.ForeignKey(help_text='What type of payment is this?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.paymenttype', verbose_name='Payment type'),
        ),
    ]
