# Generated by Django 4.1.4 on 2023-12-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_payment_paymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='standard_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standard amount to be paid, in $', max_digits=7),
        ),
    ]
