# Generated by Django 4.1.4 on 2023-12-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_alter_payment_date_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date_paid',
            new_name='date_paid_in_full',
        ),
    ]
