# Generated by Django 4.1.4 on 2023-12-31 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0052_gradinginvite_gradingresult_grading_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradinginvite',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
