# Generated by Django 5.0 on 2023-12-31 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_gradinginvite_issued_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradinginvite',
            old_name='date',
            new_name='grading_date',
        ),
        migrations.AddField(
            model_name='gradinginvite',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.payment'),
        ),
    ]
