# Generated by Django 5.0 on 2024-01-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_rename_date_gradinginvite_grading_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradinginvite',
            old_name='type',
            new_name='grading_type',
        ),
    ]
