# Generated by Django 5.0 on 2024-01-01 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_rename_type_gradinginvite_grading_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingresult',
            name='grading_invite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.gradinginvite'),
        ),
    ]
