# Generated by Django 5.0 on 2024-01-01 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_alter_gradingresult_grading_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradinginvite',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.payment'),
        ),
    ]
