# Generated by Django 5.0 on 2024-01-01 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_remove_gradinginvite_grading_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradinginvite',
            name='grading_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Grading Date'),
            preserve_default=False,
        ),
    ]
