# Generated by Django 5.0 on 2024-01-02 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_alter_gradinginvite_grading_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_due',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 15, 38, 12, 997838)),
        ),
    ]
