# Generated by Django 5.0 on 2024-01-02 15:40

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_alter_payment_date_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_due',
            field=models.DateTimeField(default=dashboard.models.time_in_a_month),
        ),
    ]
