# Generated by Django 5.0 on 2024-01-02 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_alter_payment_date_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradinginvite',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.payment'),
        ),
    ]
