# Generated by Django 5.0 on 2024-01-02 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_alter_gradinginvite_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_type', models.CharField(choices=[('MS', 'Musketeers'), ('JR', 'Juniors'), ('SN', 'Seniors'), ('JS', 'Juniors/Seniors All'), ('JD', 'Juniors/Seniors Beginner-Blue'), ('JF', 'Juniors/Seniors Red-Black'), ('PA', 'TKD Patterns/Grading'), ('BB', 'Black Belt'), ('BJ', 'BJJ/MMA'), ('BO', 'Boxing'), ('BK', 'BJJ for Kids'), ('WE', 'Weapons'), ('FC', 'Fight Class')], max_length=2)),
                ('grading_datetime', models.DateTimeField(verbose_name='Grading Date & Time')),
            ],
        ),
        migrations.AlterField(
            model_name='gradinginvite',
            name='grading_datetime',
            field=models.DateTimeField(verbose_name='Grading Date & Time'),
        ),
        migrations.AddField(
            model_name='gradinginvite',
            name='grading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.grading'),
        ),
        migrations.AddField(
            model_name='gradingresult',
            name='grading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.grading'),
        ),
    ]
