# Generated by Django 5.0 on 2024-01-02 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_alter_gradingresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradinginvite',
            name='grading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.grading'),
        ),
        migrations.AlterField(
            model_name='gradingresult',
            name='grading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.grading'),
        ),
    ]
