# Generated by Django 5.0 on 2024-01-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_alter_gradinginvite_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-belt', 'last_name']},
        ),
    ]
