# Generated by Django 5.0 on 2024-01-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_rename_grading_invite_gradingresult_gradinginvite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradingresult',
            old_name='grading_invite',
            new_name='gradinginvite',
        ),
    ]
