# Generated by Django 5.0 on 2024-01-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_alter_gradingresult_gradinginvite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradinginvite',
            options={'ordering': ['-grading__grading_datetime', '-forbelt', 'grading__grading_type', 'member__idnumber']},
        ),
    ]
