# Generated by Django 5.0 on 2024-01-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_alter_gradinginvite_forbelt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradingresult',
            old_name='grading_invite',
            new_name='gradinginvite',
        ),
    ]
