# Generated by Django 5.0.1 on 2024-01-30 21:28

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_alter_gradinginvite_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_payment_date', models.DateField()),
                ('interval', models.DurationField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount to be paid, in $', max_digits=7)),
                ('next_due', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('last_payment_date'), '+', models.F('interval')), output_field=models.DateTimeField())),
                ('member', models.ForeignKey(help_text='Who needs to pay this?', on_delete=django.db.models.deletion.PROTECT, to='dashboard.member')),
                ('payments', models.ManyToManyField(help_text='What payments are linked to this', to='dashboard.payment')),
                ('paymenttype', models.ForeignKey(help_text='Payment Type', on_delete=django.db.models.deletion.PROTECT, to='dashboard.paymenttype')),
            ],
        ),
    ]
