# Generated by Django 5.0.1 on 2024-01-30 21:47

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_paymenttype_recurring_recurringpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttype',
            name='recurring',
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='last_payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='payments',
            field=models.ManyToManyField(blank=True, help_text='What payments are linked to this', to='dashboard.payment'),
        ),
    ]
