# Generated by Django 5.0.1 on 2024-02-09 20:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_remove_paymenttype_recurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpayment',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(days=30), help_text='DD HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='paymenttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.paymenttype', verbose_name='Payment Type'),
        ),
    ]
