# Generated by Django 5.0.1 on 2024-02-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_alter_recurringpayment_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpayment',
            name='last_payment_date',
            field=models.DateField(null=True),
        ),
    ]
