# Generated by Django 5.0.1 on 2024-02-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_memberpropertytype_memberproperty'),
        ('dashboard', '0078_alter_recurringpayment_last_payment_date'),
    ]

    operations = [
    ]
