# Generated by Django 5.0.1 on 2024-02-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_alter_class_options_alter_memberproperty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='properties', to='dashboard.memberproperty'),
        ),
        migrations.AlterField(
            model_name='memberproperty',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='members', to='dashboard.member'),
        ),
    ]
