# Generated by Django 5.0.1 on 2024-02-11 16:15

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_alter_belt_options_alter_gradinginvite_forbelt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradinginvite',
            name='forbelt',
            field=models.ForeignKey(default=dashboard.models.Belt.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='dashboard.belt', verbose_name='For Belt'),
        ),
        migrations.AlterField(
            model_name='gradingresult',
            name='forbelt',
            field=models.ForeignKey(default=dashboard.models.Belt.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='dashboard.belt', verbose_name='For Belt'),
        ),
        migrations.AlterField(
            model_name='member',
            name='belt',
            field=models.ForeignKey(default=dashboard.models.Belt.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='dashboard.belt'),
        ),
    ]
