# Generated by Django 5.0.1 on 2024-02-14 15:53

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_alter_assessmentunit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='assessmentunittype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='memberproperty',
            options={'ordering': ['name'], 'verbose_name_plural': 'member properties'},
        ),
        migrations.AlterModelOptions(
            name='memberpropertytype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='recurringpayment',
            options={'ordering': ['-next_due', 'paymenttype']},
        ),
        migrations.AddField(
            model_name='class',
            name='classtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.classtype'),
        ),
        migrations.CreateModel(
            name='GradingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('style', models.ForeignKey(default=dashboard.models.Style.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='dashboard.style')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='classtype',
            name='style',
            field=models.ForeignKey(default=dashboard.models.Style.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='dashboard.style'),
        ),
        migrations.AddField(
            model_name='assessmentunittype',
            name='style',
            field=models.ForeignKey(default=dashboard.models.Style.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='dashboard.style'),
        ),
        migrations.AddField(
            model_name='award',
            name='style',
            field=models.ForeignKey(default=dashboard.models.Style.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='dashboard.style'),
        ),
        migrations.AddField(
            model_name='belt',
            name='style',
            field=models.ForeignKey(default=dashboard.models.Style.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='dashboard.style'),
        ),
        migrations.AddField(
            model_name='grading',
            name='style',
            field=models.ForeignKey(default=dashboard.models.Style.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='dashboard.style'),
        ),
        migrations.AddField(
            model_name='gradinginvite',
            name='style',
            field=models.ForeignKey(default=dashboard.models.Style.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='dashboard.style'),
        ),
        migrations.AddField(
            model_name='gradingresult',
            name='style',
            field=models.ForeignKey(default=dashboard.models.Style.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='dashboard.style'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='style',
            field=models.ForeignKey(default=dashboard.models.Style.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='dashboard.style'),
        ),
    ]
