# Generated by Django 5.0.1 on 2024-02-14 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0093_transfer_classtypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='type',
        ),
        migrations.RemoveField(
            model_name='grading',
            name='grading_type',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='classtype',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='grading',
            old_name='grading_typeNEW',
            new_name='grading_type',
        ),
    ]
