# Generated by Django 5.0.2 on 2024-02-21 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0094_remove_class_classtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grading',
            name='style',
        ),
        migrations.RemoveField(
            model_name='gradinginvite',
            name='style',
        ),
        migrations.RemoveField(
            model_name='gradingresult',
            name='style',
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.style'),
        ),
    ]
