# Generated by Django 5.0.2 on 2024-02-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0096_memberpropertytype_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belt',
            name='degree',
            field=models.IntegerField(),
        ),
    ]
