# Generated by Django 5.0.2 on 2024-02-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0097_alter_belt_degree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='belt',
            options={'ordering': ['-style', '-degree']},
        ),
    ]
