# Generated by Django 5.0.2 on 2024-02-21 09:26

import dashboard.models
from django.db import migrations, models

def make_many_belts(apps, schema_editor):
    """
        Adds the Belt object in Member.belt to the
        many-to-many relationship in Member.belts
    """
    Member = apps.get_model('dashboard', 'Member')

    for member in Member.objects.all():
        member.belts.add(member.belt)

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_alter_belt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='belts',
            field=models.ManyToManyField(default=dashboard.models.Belt.get_default_pk, related_name='belts', to='dashboard.belt'),
        ),
        migrations.RunPython(make_many_belts)
    ]
