# Generated by Django 5.0.2 on 2024-02-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0099_member_belts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name']},
        ),
        migrations.RemoveField(
            model_name='member',
            name='belt',
        ),
    ]
