# Generated by Django 5.0.2 on 2024-02-27 21:41

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0100_alter_member_options_remove_member_belt'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='belt',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('style', 'degree'), name='unique_style_degree'),
        ),
    ]
