# Generated by Django 5.0.2 on 2024-03-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0101_belt_unique_style_degree'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='memberpropertytype',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher_property', True)), fields=('style', 'teacher_property'), name='unique_teacher_property_style'),
        ),
    ]
