name: Django Tests

on:
  # Set your workflow to run on push events to the develop and all feature branches
  push:
    branches:
      - staging
      - feature/*
  # Set your workflow to run on pull request events that target the main branch
  pull_request:
    branches: 
      - main

  workflow_dispatch:
    branches:
      - main
      - staging
      - feature/*

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd tkdmanager
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd tkdmanager
        python manage.py test
