name: Lint

on: [push, pull_request]

jobs:  
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd tkdmanager
        pip install -r requirements.txt
    - name: Install Linters
      run: |
        pip install pylint
        pip install flake8
        pip install bandit
    - name: Run Linters
      run: |
        echo "\nRunning Pylint against source and test files...\n"
        pylint --rcfile=setup.cfg **/*.py --ignore=manage.py --ignore=migrations/
        echo "\n}Running Flake8 against source and test files...\n"
        flake8
        echo "\nRunning Bandit against source files...\n"
        bandit -r --ini setup.cfg